#
# Makefile for the accelerometer drivers.
#

# Each configuration option enables a list of files.



obj-$(CONFIG_HUAWEI_FEATURE_ACCELEROMETER_ADXL345)	+= gsdev.o
obj-$(CONFIG_HUAWEI_FEATURE_ACCELEROMETER_ST_L1S35DE)	+= gs_st.o

